/**
 * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 *
 * Maps each original product image to its optimized WebP sibling. 23
 * assets, 14.2MB -> 1.5MB served.
 * Originals remain on disk as the fallback for any asset not listed here.
 *
 * Regenerate: npm run optimize:images
 */
export const IMAGE_VARIANTS: Record<string, string> = {
  'images/products/2-5-inch-4-part-metal-grinder-rick-and-morty-printed.png': 'images/products/2-5-inch-4-part-metal-grinder-rick-and-morty-printed.webp',
  'images/products/4-part-metal-skull-grinder-2-inch.png': 'images/products/4-part-metal-skull-grinder-2-inch.webp',
  'images/products/alien-go-cotton-filter-tips-pack-of-200.png': 'images/products/alien-go-cotton-filter-tips-pack-of-200.webp',
  'images/products/cherry-pipe.png': 'images/products/cherry-pipe.webp',
  'images/products/clear-beaker.png': 'images/products/clear-beaker.webp',
  'images/products/g-rollz-medicago-cbd-infused-plant-rolling-paper.jpg': 'images/products/g-rollz-medicago-cbd-infused-plant-rolling-paper.webp',
  'images/products/grinder-classic.jpg': 'images/products/grinder-classic.webp',
  'images/products/hb109-silicon.png': 'images/products/hb109-silicon.webp',
  'images/products/papers-ocb.jpg': 'images/products/papers-ocb.webp',
  'images/products/phoenix-10-3d-bloody-monster-design-7mm-glass-bong.png': 'images/products/phoenix-10-3d-bloody-monster-design-7mm-glass-bong.webp',
  'images/products/phoenix-10-3d-evil-eyes-monster-design-7mm-glass-bong.png': 'images/products/phoenix-10-3d-evil-eyes-monster-design-7mm-glass-bong.webp',
  'images/products/phoenix-10-3d-skull-monster-design-7mm-glass-bong.jpeg': 'images/products/phoenix-10-3d-skull-monster-design-7mm-glass-bong.webp',
  'images/products/phoenix-13-inch-detachable-freezable-coil-beaker-glass-bong.jpeg': 'images/products/phoenix-13-inch-detachable-freezable-coil-beaker-glass-bong.webp',
  'images/products/phoenix-14-inch-decal-printed-metal-tray.png': 'images/products/phoenix-14-inch-decal-printed-metal-tray.webp',
  'images/products/phoenix-15-inch-monster-percolator-streight-glass-bong.jpeg': 'images/products/phoenix-15-inch-monster-percolator-streight-glass-bong.webp',
  'images/products/phoenix-17-inch-dual-mashroom-percolator-bamboo-glass-bong.png': 'images/products/phoenix-17-inch-dual-mashroom-percolator-bamboo-glass-bong.webp',
  'images/products/phoenix-18-inch-decal-printed-heavy-ice-catcher-beaker-bong.jpeg': 'images/products/phoenix-18-inch-decal-printed-heavy-ice-catcher-beaker-bong.webp',
  'images/products/phoenix-2-inch-4-part-metal-grinder-pockemon-printed.png': 'images/products/phoenix-2-inch-4-part-metal-grinder-pockemon-printed.webp',
  'images/products/phoenix-5-inch-jumbo-smoking-pipe.png': 'images/products/phoenix-5-inch-jumbo-smoking-pipe.webp',
  'images/products/phoenix-5-inch-multi-colored-silicon-beaker-bong.jpeg': 'images/products/phoenix-5-inch-multi-colored-silicon-beaker-bong.webp',
  'images/products/richer-papers.png': 'images/products/richer-papers.webp',
  'images/products/rick-morty-tray.png': 'images/products/rick-morty-tray.webp',
  'images/products/wooden-grinder.png': 'images/products/wooden-grinder.webp',
};

/**
 * Lookup table covering both path shapes. seed.json stores absolute
 * ("/images/products/x.png") while the manifest keys are relative
 * ("images/products/x.png"); a single map cannot serve both without
 * duplicating itself, and mutating IMAGE_VARIANTS would corrupt iteration for
 * anything that walks it. Kept separate for that reason.
 */
const LOOKUP: Record<string, string> = { ...IMAGE_VARIANTS };
for (const [key, value] of Object.entries(IMAGE_VARIANTS)) {
  LOOKUP[`/${key}`] = `/${value}`;
}

/**
 * Optimized URL for a product image; falls through to the original when the
 * asset has no WebP sibling.
 */
export function optimizedImage(src: string | undefined | null): string | undefined {
  if (!src) return undefined;
  return LOOKUP[src] ?? src;
}
